name = "Gensokyo Reimagined QOL"
author = "Taiyou06"
version = "1.13.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "272498dfe07ae505b74c9b4ea7da66561671e1774ff06f9e998e6f57ed73d5af"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
