name = "Gensokyo Reimagined QOL"
author = "Taiyou06"
version = "1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d830e49ed4b8309b8ced8347fde8dbc70c20f5a29dc068e875d4e9d0c300ed5"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
