name = "Gensokyo Reimagined QOL"
author = "Taiyou06"
version = "1.13.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "195fe0533962495ab15c60fcb9fca3204bb4cd66d222e112772e5e92e97e3ce4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
